[package]
name = "bittor_client"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["crates/bittorrent_core", "crates/bencode", "crates/url_encode"]

[workspace.dependencies]
num = "0.4.3"
sha1 = "0.11.0"
bittorrent_core = {path = "crates/bittorrent_core"}
bencode = {path = "crates/bencode"}
reqwest = "0.13.4"
async-trait = "0.1.92"
rand = "0.10.2"
thiserror = "2.0.20"

[dependencies]
bittorrent_core = {workspace = true}
