[package]
name = "bittorrent_core"
version = "0.1.0"
edition = "2024"

[dependencies]
bencode = {workspace = true }
sha1 = {workspace = true }
reqwest = { workspace = true }
async-trait = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
url_encode = {workspace = true}
thiserror = { workspace = true }
